name: Docker Push in Elastic Container Registry

on:
    push:
        branches:
            - main

env:
  AWS_REGION: ap-southeast-1
  APP_NAME: japp
  VERSION: 0.1.0

jobs:
    awsECRpush:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              name: Checkout code
            - uses: aws-actions/configure-aws-credentials@v4
              name: Configure AWS Credentials
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
                aws-region: ${{ env.AWS_REGION }}
            - uses: aws-actions/amazon-ecr-login@v2
              id: login-ecr
              name: Login to ECR
            # - uses: docker/login-action@v3
            #   name: Docker login
            #   with:
            #     username: AWS
            #     password: ${{ steps.login-ecr.outputs.docker_username }}
            - name: Build and Push
              uses: docker/build-push-action@v6
              with:
                context: ./deploy-with-ecs/japp
                push: true
                tags: |
                   ${{ steps.login-ecr.outputs.registry }}/imshakil/${{ env.APP_NAME }}:${{ env.VERSION }}
                   ${{ steps.login-ecr.outputs.registry }}/imshakil/${{ env.APP_NAME }}:latest
